name: athena-meta
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=2.7.15
  - pip
  - athena_meta
  - bioconda::pysam
  - bioconda::flye
  - bioconda::megahit
  - biopython
  - bioconda::samtools
  - bioconda::seqtk
  - bioconda::bwa
  - bioconda::metabat2
  - bioconda::spades
  - bioconda::quickmerge
  - pip:
    - scikit-learn
    - pandas
    - tqdm