name: pangaea
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - snakemake
  - bioconda::pysam
  - bioconda::flye
  - bioconda::megahit
  - biopython
  - bioconda::jellyfish
  - bioconda::samtools
  - bioconda::seqtk
  - bioconda::bwa
  - bioconda::metabat2
  - bioconda::metaphlan
  - bioconda::spades
  - bioconda::quickmerge
  - pip:
    - scikit-learn
    - pandas
    - tqdm