name: pangaea
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - snakemake
  - bioconda::pysam
  - bioconda::flye=2.8.3
  - bioconda::megahit
  - biopython
  - bioconda::jellyfish
  - bioconda::samtools
  - bioconda::seqtk
  - bioconda::bwa
  - bioconda::metabat2
  - bioconda::metaphlan
  - bioconda::spades
  - bioconda::quickmerge
  - bioconda::htslib
  - bioconda::metaplatanus
  - conda-forge::cmake=3.29.4
  - conda-forge::gcc_linux-64=15.1.0
  - conda-forge::gxx_linux-64=15.1.0
  - pigz
  - fastq-tools
  - pip:
    - scikit-learn
    - pandas
    - tqdm